### ISSUE TITLE
[I tuoi obiettivi] todo

### ISSUE THREAD

**Issue by theCesp** [theCesp/done#3]
- [ ] ordinamento per: Label, % Tempo, %Goal:
- [ ] menu ordinamento espando su desktop
- [ ] menu ordinamento compresso su app
- [ ] suddivisione raggruppamenti
- [ ] decidere pallette di colori
- [ ] linkare a dettaglio obiettivo
- [ ] linkare a nuovo obiettivo
